### ISSUE TITLE
When I try to use it on Mac OS Catalina I receive this error

### ISSUE THREAD

**Issue by Enderpearl330** [KevinAlavik/chrome-pie#1]
src/cmd/main.c:8:5: error: first parameter of 'main' (argument count) must be of
      type 'int'
int main(char* argc, char* argv[]) {
    ^
src/cmd/main.c:9:17: warning: result of comparison against a string literal is
      unspecified (use strncmp instead) [-Wstring-compare]
    if (argv[1] == "--help") {
                ^  ~~~~~~~~
src/cmd/main.c:12:17: warning: result of comparison against a string literal is
      unspecified (use strncmp instead) [-Wstring-compare]
    if (argv[1] == "run") {
                ^  ~~~~~
src/cmd/main.c:13:18: warning: using the result of an assignment as a condition
      without parentheses [-Wparentheses]
      if(argv[2] = "--help") {
         ~~~~~~~~^~~~~~~~~~
src/cmd/main.c:13:18: note: place parentheses around the assignment to silence
      this warning
      if(argv[2] = "--help") {
                 ^
         (                 )
src/cmd/main.c:13:18: note: use '==' to turn this assignment into an equality
      comparison
      if(argv[2] = "--help") {
                 ^
                 ==
src/cmd/main.c:16:21: warning: result of comparison against a string literal is
      unspecified (use strncmp instead) [-Wstring-compare]
      } if (argv[2] == "--stable ") {
                    ^  ~~~~~~~~~~~
4 warnings and 1 error generated.
Successfully compiled pie, (./pie)
Now check the install guide (https://github.com/KevinAlavik/chrome-pie/blob/main/INSTALL.md) just skip the Build and Install part. And you should be good to go
Password:
mv: rename ./pie to /usr/local/bin/pie: No such file or directory
chrome-pie %

**Comment by KevinAlavik** [comment]
Yep the command is currently broken! I'm working on an fix

**Comment by KevinAlavik** [comment]
Should be fixed!
