### ISSUE TITLE
suggestion: use argp (or another arg parsing solution)

### ISSUE THREAD

**Issue by crumbtoo** [KevinAlavik/chrome-pie#2]
the long else-if chain in main.c could be significantly simplified. currently looks like it will grow into a pain to maintain :3. (i could work on this if you'd like)

**Comment by KevinAlavik** [comment]
If you could do this and just make an pullrequest that would be awesome!

**Comment by crumbtoo** [comment]
are you okay with a syntax like ``pie [global options]... [command] [command options | arguments]...``?

**Comment by KevinAlavik** [comment]
im sorry i dont understand could you give me an example

**Comment by crumbtoo** [comment]
`pie --option command --opt arg1 arg2`

**Comment by KevinAlavik** [comment]
Oh ok that works
