### ISSUE TITLE
Install guide hard to understand 

### ISSUE THREAD

**Issue by Enderpearl330** [KevinAlavik/chrome-pie#3]
Running the ./install.sh worked just fine, however running the pie command (wether its pie run or pie pico) with either my chromebook or my pi pico connected doesn’t quite seem to do anything after waiting a few minutes. Am I doing something wrong, or is there some sort of issue happening?

**Comment by KevinAlavik** [comment]
Its work in progress rn all of the working feautures are private, sorry
