### ISSUE TITLE
use of system(), sudo, and chmod

### ISSUE THREAD

**Issue by crumbtoo** [KevinAlavik/chrome-pie#6]
security no-no's :3. for `system()`, all current uses are just easily avoided: just print from C instead of using ascii.sh. for `sudo`, there really is no reason to be throwing it around like this. almost none of these commands require root permissions, and if they did, the user can run the program with `sudo` themselves. similar situation with `chmod +rwx`

**Comment by KevinAlavik** [comment]
True true
